// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_VOICEVOX_CS_WRT_0_H
#define WINRT_VOICEVOX_CS_WRT_0_H
WINRT_EXPORT namespace winrt::VOICEVOX_CS_WRT
{
    enum class VoiceVoxResult_ENUM : int32_t
    {
        SUCCEED = 0,
        NOT_LOADED_OPENJTALK_DICT = 1,
    };
    struct IVoiceVoxCoreWrapper;
    struct IVoiceVoxCoreWrapperFactory;
    struct VoiceVoxCoreWrapper;
}
namespace winrt::impl
{
    template <> struct category<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper>{ using type = interface_category; };
    template <> struct category<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory>{ using type = interface_category; };
    template <> struct category<winrt::VOICEVOX_CS_WRT::VoiceVoxCoreWrapper>{ using type = class_category; };
    template <> struct category<winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM>{ using type = enum_category; };
    template <> inline constexpr auto& name_v<winrt::VOICEVOX_CS_WRT::VoiceVoxCoreWrapper> = L"VOICEVOX_CS_WRT.VoiceVoxCoreWrapper";
    template <> inline constexpr auto& name_v<winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM> = L"VOICEVOX_CS_WRT.VoiceVoxResult_ENUM";
    template <> inline constexpr auto& name_v<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper> = L"VOICEVOX_CS_WRT.IVoiceVoxCoreWrapper";
    template <> inline constexpr auto& name_v<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory> = L"VOICEVOX_CS_WRT.IVoiceVoxCoreWrapperFactory";
    template <> inline constexpr guid guid_v<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper>{ 0x9D9357BD,0x9CBC,0x501D,{ 0x92,0xD0,0x46,0xB3,0xAC,0xCA,0xB3,0xE5 } }; // 9D9357BD-9CBC-501D-92D0-46B3ACCAB3E5
    template <> inline constexpr guid guid_v<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory>{ 0x8E158215,0xA7FE,0x5512,{ 0xBD,0x93,0x54,0x39,0x27,0x71,0x2C,0x9E } }; // 8E158215-A7FE-5512-BD93-543927712C9E
    template <> struct default_interface<winrt::VOICEVOX_CS_WRT::VoiceVoxCoreWrapper>{ using type = winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper; };
    template <> struct abi<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall InitializeCore(bool, int32_t, bool, bool*) noexcept = 0;
            virtual int32_t __stdcall voicevox_load_openjtalk_dict(void*, int32_t*) noexcept = 0;
            virtual int32_t __stdcall voicevox_error_result_to_message(int32_t, void**) noexcept = 0;
            virtual int32_t __stdcall voicevox_tts(void*, int64_t, int64_t, int64_t, int32_t*) noexcept = 0;
            virtual int32_t __stdcall voicevox_tts_from_kana(void*, int64_t, int64_t, int64_t, int32_t*) noexcept = 0;
            virtual int32_t __stdcall voicevox_free_wav(int64_t) noexcept = 0;
            virtual int32_t __stdcall load_model(int64_t, bool*) noexcept = 0;
            virtual int32_t __stdcall is_model_loaded(int64_t, bool*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_VOICEVOX_CS_WRT_IVoiceVoxCoreWrapper
    {
        auto InitializeCore(bool use_cpu, int32_t cpu_numthreads, bool load_allmodels) const;
        auto voicevox_load_openjtalk_dict(param::hstring const& dpath) const;
        auto voicevox_error_result_to_message(winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM const& result_code) const;
        auto voicevox_tts(param::hstring const& text, int64_t speaker_id, int64_t output_binary_size, int64_t output_wav) const;
        auto voicevox_tts_from_kana(param::hstring const& text, int64_t speaker_id, int64_t output_binary_size, int64_t output_wav) const;
        auto voicevox_free_wav(int64_t wav) const;
        auto load_model(int64_t speaker_id) const;
        auto is_model_loaded(int64_t speaker_id) const;
    };
    template <> struct consume<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapper>
    {
        template <typename D> using type = consume_VOICEVOX_CS_WRT_IVoiceVoxCoreWrapper<D>;
    };
    template <typename D>
    struct consume_VOICEVOX_CS_WRT_IVoiceVoxCoreWrapperFactory
    {
        auto CreateInstance(param::hstring const& coredll_path) const;
    };
    template <> struct consume<winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory>
    {
        template <typename D> using type = consume_VOICEVOX_CS_WRT_IVoiceVoxCoreWrapperFactory<D>;
    };
}
#endif
