// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_VOICEVOX_CS_WRT_1_H
#define WINRT_VOICEVOX_CS_WRT_1_H
#include "winrt/impl/VOICEVOX_CS_WRT.0.h"
WINRT_EXPORT namespace winrt::VOICEVOX_CS_WRT
{
    struct __declspec(empty_bases) IVoiceVoxCoreWrapper :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IVoiceVoxCoreWrapper>
    {
        IVoiceVoxCoreWrapper(std::nullptr_t = nullptr) noexcept {}
        IVoiceVoxCoreWrapper(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IVoiceVoxCoreWrapperFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IVoiceVoxCoreWrapperFactory>
    {
        IVoiceVoxCoreWrapperFactory(std::nullptr_t = nullptr) noexcept {}
        IVoiceVoxCoreWrapperFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
