#pragma once
#include "VoiceVoxCore_SoundResult.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::VOICEVOX_CS_WRT::implementation
{
    struct VoiceVoxCore_SoundResult : VoiceVoxCore_SoundResultT<VoiceVoxCore_SoundResult>
    {
        VoiceVoxCore_SoundResult() = default;

        VoiceVoxCore_SoundResult(winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM const& result_v, int64_t out_size, int64_t out_wav_ptr);
        winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM RESULT_VALUE();
        void RESULT_VALUE(winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM const& value);
        int64_t OUTPUT_SIZE();
        void OUTPUT_SIZE(int64_t value);
        int64_t OUTPUT_WAV_PTR();
        void OUTPUT_WAV_PTR(int64_t value);
    private:
        VoiceVoxResult_ENUM _result_value;
        int64_t _output_size;
        int64_t _output_wav_ptr;
    };
}
namespace winrt::VOICEVOX_CS_WRT::factory_implementation
{
    struct VoiceVoxCore_SoundResult : VoiceVoxCore_SoundResultT<VoiceVoxCore_SoundResult, implementation::VoiceVoxCore_SoundResult>
    {
    };
}
