// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#include "winrt/VOICEVOX_CS_WRT.h"
#include "winrt/Windows.Foundation.h"
namespace winrt::VOICEVOX_CS_WRT::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) VoiceVoxCoreWrapper_base : implements<D, VOICEVOX_CS_WRT::VoiceVoxCoreWrapper, winrt::Windows::Foundation::IClosable, I...>
    {
        using base_type = VoiceVoxCoreWrapper_base;
        using class_type = VOICEVOX_CS_WRT::VoiceVoxCoreWrapper;
        using implements_type = typename VoiceVoxCoreWrapper_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"VOICEVOX_CS_WRT.VoiceVoxCoreWrapper";
        }
    };
}
namespace winrt::VOICEVOX_CS_WRT::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) VoiceVoxCoreWrapperT : implements<D, winrt::Windows::Foundation::IActivationFactory, winrt::VOICEVOX_CS_WRT::IVoiceVoxCoreWrapperFactory, I...>
    {
        using instance_type = VOICEVOX_CS_WRT::VoiceVoxCoreWrapper;

        hstring GetRuntimeClassName() const
        {
            return L"VOICEVOX_CS_WRT.VoiceVoxCoreWrapper";
        }
        auto CreateInstance(hstring const& coredll_path)
        {
            return make<T>(coredll_path);
        }
        [[noreturn]] winrt::Windows::Foundation::IInspectable ActivateInstance() const
        {
            throw hresult_not_implemented();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_VOICEVOXCOREWRAPPER_XAML_G_H) || __has_include("VoiceVoxCoreWrapper.xaml.g.h")

#include "VoiceVoxCoreWrapper.xaml.g.h"

#else

namespace winrt::VOICEVOX_CS_WRT::implementation
{
    template <typename D, typename... I>
    using VoiceVoxCoreWrapperT = VoiceVoxCoreWrapper_base<D, I...>;
}

#endif
