// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

void* winrt_make_VOICEVOX_CS_WRT_VoiceVoxCore_SoundResult()
{
    return winrt::detach_abi(winrt::make<winrt::VOICEVOX_CS_WRT::factory_implementation::VoiceVoxCore_SoundResult>());
}
WINRT_EXPORT namespace winrt::VOICEVOX_CS_WRT
{
    VoiceVoxCore_SoundResult::VoiceVoxCore_SoundResult(winrt::VOICEVOX_CS_WRT::VoiceVoxResult_ENUM const& result_v, int64_t out_size, int64_t out_wav_ptr) :
        VoiceVoxCore_SoundResult(make<VOICEVOX_CS_WRT::implementation::VoiceVoxCore_SoundResult>(result_v, out_size, out_wav_ptr))
    {
    }
}
