namespace VOICEVOX_CS_WRT
{
    [default_interface]
    runtimeclass VoiceVoxCoreWrapper: Windows.Foundation.IClosable
    {
        VoiceVoxCoreWrapper(String coredll_path);
        Boolean InitializeCore(Boolean use_cpu, Int32 cpu_numthreads, Boolean load_allmodels);
        VoiceVoxResult_ENUM voicevox_load_openjtalk_dict(String dpath);
        String voicevox_error_result_to_message(VoiceVoxResult_ENUM result_code);
        VoiceVoxCore_SoundResult voicevox_tts(String text, Int64 speaker_id);
        VoiceVoxCore_SoundResult voicevox_tts_from_kana(String text, Int64 speaker_id);
        void voicevox_free_wav(Int64 wav);
        Boolean load_model(Int64 speaker_id);
        Boolean is_model_loaded(Int64 speaker_id);
    }
    runtimeclass VoiceVoxCore_SoundResult{
        VoiceVoxResult_ENUM RESULT_VALUE;
        Int64 OUTPUT_SIZE;
        Int64 OUTPUT_WAV_PTR;
        VoiceVoxCore_SoundResult(VoiceVoxResult_ENUM result_v,Int64 out_size, Int64 out_wav_ptr);
    }
    enum VoiceVoxResult_ENUM {

        SUCCEED = 0,
        NOT_LOADED_OPENJTALK_DICT = 1
    };
}
