// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

void* winrt_make_VOICEVOX_CS_WRT_VoiceVoxCoreWrapper()
{
    return winrt::detach_abi(winrt::make<winrt::VOICEVOX_CS_WRT::factory_implementation::VoiceVoxCoreWrapper>());
}
WINRT_EXPORT namespace winrt::VOICEVOX_CS_WRT
{
    VoiceVoxCoreWrapper::VoiceVoxCoreWrapper(param::hstring const& coredll_path) :
        VoiceVoxCoreWrapper(make<VOICEVOX_CS_WRT::implementation::VoiceVoxCoreWrapper>(coredll_path))
    {
    }
}
